# -*- coding: utf-8 -*-
"""Sentiment Analysis using NLP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w--VqXXPLV5ojoUWoiwrlv6RTXyQaCad
"""

# ==================== STEP 1: Load Dataset ====================
import pandas as pd

# First, download the dataset from Kaggle or use uploaded file
# If you have the file uploaded to Colab:
df = pd.read_csv('Tweets.csv')  # Make sure the file name matches
print("Answer for Q1:", df.shape)

# Keep only necessary columns
df = df[["airline_sentiment", "text"]]
print("Dataset shape before splitting:", df.shape)

# ==================== STEP 2: Preprocess Text ====================
import nltk
import string
import re
from nltk.stem.porter import PorterStemmer

nltk.download('stopwords')
nltk.download('punkt')
from nltk.corpus import stopwords

ps = PorterStemmer()

def clean_text(text):
    text = text.lower()
    text = re.sub(r'http.?://[^\s]+[\s]?', '', text)
    text = nltk.word_tokenize(text)
    y = []
    for i in text:
        if i not in stopwords.words('english'):
            y.append(i)
    text = y[:]
    y.clear()
    for i in text:
        y.append(ps.stem(i))
    return " ".join(y)

# Apply cleaning
df['text_cleaned'] = df['text'].apply(clean_text)

# Check first tweet cleaning (Question 5)
print("\nQuestion 5: First tweet after cleaning:")
print("Original:", df['text'].iloc[0])
print("Cleaned:", df['text_cleaned'].iloc[0])

# ==================== STEP 3: Feature Extraction ====================
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(max_features=3000)
X = tfidf.fit_transform(df['text_cleaned']).toarray()
Y = df['airline_sentiment'].values

print("\nQuestion 4: Shape of X:", X.shape)
print("Answer for Q4:", X.shape)

# ==================== STEP 4: Train Models ====================
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=2)

# Random Forest
rf = RandomForestClassifier()
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
rf_accuracy = accuracy_score(y_test, y_pred_rf)
print("\nQuestion 2: Random Forest accuracy:", round(rf_accuracy, 2))
print("Answer for Q2:", round(rf_accuracy, 2))

# Multinomial Naive Bayes
nb = MultinomialNB()
nb.fit(X_train, y_train)
y_pred_nb = nb.predict(X_test)
nb_accuracy = accuracy_score(y_test, y_pred_nb)
print("\nQuestion 3: Multinomial Naive Bayes accuracy:", round(nb_accuracy, 2))
print("Answer for Q3:", round(nb_accuracy, 2))

# ==================== STEP 5: Answer Remaining Questions ====================
# Question about negative sentiment count
negative_count = df[df['airline_sentiment'] == 'negative'].shape[0]
print("\nQuestion 6: Negative sentiment count:", negative_count)
print("Answer for Q6:", negative_count)

# Question about neutral sentiment count
neutral_count = df[df['airline_sentiment'] == 'neutral'].shape[0]
print("\nQuestion 7: Neutral sentiment count:", neutral_count)
print("Answer for Q7:", neutral_count)

# ==================== BONUS: Group by to verify ====================
print("\n\nVerification using groupby:")
print(df.groupby('airline_sentiment').size())